### ISSUE TITLE
Create a list of complex phonetic words  

### ISSUE THREAD

**Issue by edouarde1** [LoganParker/The-Speaking-Portal-Project#193]
**Is this related to a problem? Please describe.**

In order to properly test progress with the client this Friday, we would like to have our demo attempt to speak complex words. 

**Describe the solution you'd like**

A list words should added into a test doc into the repo.

**Comment by vnajack** [comment]
I looked at some advanced reading comprehension sites (so that we have more complex words in our paragraphs) and found the following for some ideas

- [Dirty Britain](https://www.usingenglish.com/comprehension/29.html)
- [Difficult GMAT Passage](https://www.kaptest.com/study/gmat/high-level-gmat-reading-comprehension-practice/)

**Comment by vnajack** [comment]
I'm closing this issue since we have more complex test files now
